In [863]:
import numpy as np

In [864]:
# Írj egy olyan fügvényt, ami megfordítja egy 2d array oszlopait
# Be: [[1,2],[3,4]]
# Ki: [[2,1],[4,3]]
# column_swap()

In [865]:
def column_swap(array: np.array) -> np.array:
    array[:, [1, 0]] = array[:, [0, 1]]
    return array

[[2 1]
 [4 3]]


In [866]:
#Készíts egy olyan függvényt ami összehasonlít két array-t és adjon vissza egy array-ben, hogy hol egyenlőek 
# Pl Be: [7,8,9], [9,8,7] 
# Ki: [1]
# compare_two_array()
# egyenlő elemszámúakra kell csak hogy működjön

In [867]:
def compare_two_array(array1: np.array, array2: np.array) -> np.array:
    return np.where(array1 == array2)[0]

[1]


In [868]:
#Készíts egy olyan függvényt, ami vissza adja a megadott array dimenzióit:
# Be: [[1,2,3], [4,5,6]]
# Ki: "sor: 2, oszlop: 3, melyseg: 1"
# get_array_shape()
# 3D-vel még műküdnie kell!

In [869]:
import numpy as np
def get_array_shape(array: np.array) -> np.array:
    dimensions = array.shape
    sor = dimensions[0]
    oszlop = dimensions[1] if len(dimensions) >= 2 else 1
    melyseg = dimensions[2] if len(dimensions) >= 3 else 1
    return f"sor: {sor}, oszlop: {oszlop}, melyseg: {melyseg}"

sor: 2, oszlop: 3, melyseg: 1


In [870]:
# Készíts egy olyan függvényt, aminek segítségével elő tudod állítani egy neurális hálózat tanításához szükséges Y-okat egy numpy array-ből. 
#Bementként add meg az array-t, illetve hogy mennyi class-od van. Kimenetként pedig adjon vissza egy 2d array-t, ahol a sorok az egyes elemek. Minden nullákkal teli legyen és csak ott álljon egyes, ahol a bementi tömb megjelöli
# Be: [1, 2, 0, 3], 4
# Ki: [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# encode_Y()

In [871]:
def encode_Y(array: np.array, size: int) -> np.array:
    result = np.zeros((len(array), size))
    for i, a in enumerate(array):
        result[i, a] = 1
        
    return result

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [872]:
# A fenti feladatnak valósítsd meg a kiértékelését. Adj meg a 2d array-t és adj vissza a decodolt változatát
# Be:  [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# Ki:  [1, 2, 0, 3]
# decode_Y()

In [873]:
def decode_Y(array: np.array) -> np.array:
    result = np.zeros(len(array))
    for i, a in enumerate(array):
        result[i] = np.where(a == 1)[0][0]
        
    return result

[1. 2. 0. 3.]


In [874]:
# Készíts egy olyan függvényt, ami képes kiértékelni egy neurális háló eredményét! Bemenetként egy listát és egy array-t és adja vissza a legvalószínübb element a listából.
# Be: ['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]. 
# Ki: 'szilva'
# eval_classification()

In [875]:
def eval_classification(options: np.array, probabilities: np.array) -> str:
    return options[probabilities.argmax(axis=0)]

szilva


In [876]:
# Készíts egy olyan függvényt, ahol az 1D array-ben a páratlan számokat -1-re cseréli
# Be: [1,2,3,4,5,6]
# Ki: [-1,2,-1,4,-1,6]
# repalce_odd_numbers()

In [877]:
def replace_odd_numbers(array: np.array) -> np.array:
    return np.where(array % 2 == 1, -1, array)

[-1  2 -1  4 -1  6]


In [878]:
# Készíts egy olyan függvényt, ami egy array értékeit -1 és 1-re változtatja, attól függően, hogy az adott elem nagyobb vagy kisebb a paraméterként megadott számnál.
# Ha a szám kisebb mint a megadott érték, akkor -1, ha nagyobb vagy egyenlő, akkor pedig 1.
# Be: [1, 2, 5, 0], 2
# Ki: [-1, 1, 1, -1]
# replace_by_value()

In [879]:
def replace_by_value(array: np.array, threshold: int) -> np.array:
    return np.where(array < threshold, -1, 1)

[-1  1  1 -1]


In [880]:
# Készítsd egy olyan függvényt, ami az array értékeit összeszorozza és az eredmény visszaadja
# Be: [1,2,3,4]
# Ki: 24
# array_multi()
# Ha több dimenziós a tömb, akkor az egész tömb elemeinek szorzatával térjen vissza

In [881]:
def array_multi(array: np.array) -> int:
    return np.prod(array)

24


In [882]:
# Készítsd egy olyan függvényt, ami a 2D array értékeit összeszorozza és egy olyan array-el tér vissza, aminek az elemei a soroknak a szorzata
# Be: [[1, 2], [3, 4]]
# Ki: [2, 12]
# array_multi_2d()

In [883]:
def array_multi_2d(array: np.array) -> np.array:
    return np.prod(array, axis=1)

[ 2 12]


In [884]:
# Készíts egy olyan függvényt, amit egy meglévő numpy array-hez készít egy bordert nullásokkal. Bementként egy array-t várjon és kimenetként egy array jelenjen meg aminek van border-je
# Be: [[1,2],[3,4]]
# Ki: [[0,0,0,0],[0,1,2,0],[0,3,4,0],[0,0,0,0]]
# add_border()

In [885]:
def add_border(array: np.array) -> np.array:
    shape = np.array(array.shape) + 2
    result = np.zeros(shape)
    result[1:-1, 1:-1] = array
    return result

[[0. 0. 0. 0.]
 [0. 1. 2. 0.]
 [0. 3. 4. 0.]
 [0. 0. 0. 0.]]


In [886]:
# Készíts egy olyan függvényt ami két dátum között felsorolja az összes napot.
# Be: '2023-03', '2023-04'
# Ki: ['2023-03-01', '2023-03-02', .. , '2023-03-31',]
# list_days()

In [887]:
def list_days(date1, date2) -> np.array:
    return np.arange(date1, date2, dtype='datetime64[D]')

['2023-03-01' '2023-03-02' '2023-03-03' '2023-03-04' '2023-03-05'
 '2023-03-06' '2023-03-07' '2023-03-08' '2023-03-09' '2023-03-10'
 '2023-03-11' '2023-03-12' '2023-03-13' '2023-03-14' '2023-03-15'
 '2023-03-16' '2023-03-17' '2023-03-18' '2023-03-19' '2023-03-20'
 '2023-03-21' '2023-03-22' '2023-03-23' '2023-03-24' '2023-03-25'
 '2023-03-26' '2023-03-27' '2023-03-28' '2023-03-29' '2023-03-30'
 '2023-03-31']


In [888]:
# Írj egy fügvényt ami vissza adja az aktuális dátumot az alábbi formában: YYYY-MM-DD
# Be:
# Ki: 2017-03-24 

In [889]:
def get_act_date() -> np.datetime64:
    return np.datetime64('today', 'D')

2023-03-08


In [890]:
# Írj egy olyan függvényt ami visszadja, hogy mennyi másodperc telt el 1970 január 01. 00:00:00 óta.
# Be: 
# Ki: másodpercben az idó, int-é kasztolva
# sec_from_1970()


In [891]:
def sec_from_1970() -> int:
    current = np.datetime64('today', 'D')
    old = np.datetime64("1970-01-01")
    return int((current - old) / np.timedelta64(1, 's'))

1678233600
